allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")

    if (project.name != "app") {
        afterEvaluate { proj ->
            if (proj.plugins.hasPlugin("com.android.library")) {
                proj.android {
                    if (namespace == null) {
                        namespace proj.group
                    }
                    compileSdkVersion 35
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
